<?php
/***********************************************************************
 * -  Copyright ©, 2017-2017，Lr double
 * -  File name : .php
 * -  Author : Lr double   Version: 1.0    Dete: 2017-3-27 19:10:16
 * -  Description ：//Objecti操作控制器、
 * -  Others :      //其他内容说明
 * -  Function List ：//主要函数列表，每条记录包含函数名及功能简要说明
 * -  History ：//暂无修改记录
 ***********************************************************************/

namespace tea\controllers;

use tea\models\RBAC;
use tea\models\Users;
use Yii;
use yii\web\Controller;
use yii\web\Response;


class ObjectController extends Controller
{
    public $enableCsrfValidation = false;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        Yii::$app->response->format = Response::FORMAT_JSON;
        Yii::$app->language         = 'zh-CN';
    }


    /**
     * 判断用户是否登录、已经用户是否存在操作权限
     * @param \yii\base\Action $action
     * @return bool|Response | array
     */

    public function beforeAction($action)
    {

        /* 开发模拟用户登录 */
        $user = new Users();
        $user->login(['phone'=>'15888888888','password'=>'15888888888']);

        /* 开始时刻更新权限表 */
        RBAC::initAuth();

        if($action->id == 'login')
        {
            return true;
        }

        /**
         * 检查session值是否正常、不正常将跳转到登录界面
         */
        if (empty(Yii::$app->session->get('shoper_id')) &&
            empty(Yii::$app->session->get('user_id')) )
        {
            return $this->redirect(['object/login']);
        }

        $auto = \Yii::$app->authManager;
        $users = $auto->getPermissionsByUser(\Yii::$app->user->id);
//
//        var_dump($users);
//        die();
        //判断是是否有权限
        if(!RBAC::validateRole($action->controller->route)){
            die(json_encode(['code'=>-2,'msg'=>Yii::t('app','rabc_no_prieate')]));
        }

        return true;
    }

    /**
     * 返回ajax数组
     * @param $data array 数组
     * @return array 返回ajax
     */
    public function returnAjax($data)
    {
        return [
                'code'=>$data['code'],
                'msg'=>$data['msg'],
                'data'=>empty($data['data']) ? [] :$data['data']
        ];
    }

    /*
     * 返回提示用户登录
     * */
    public function actionLogin()
    {
        return $this->returnAjax(['code'=>-1,'msg'=>'请登录']);
    }

    private function Rabc()
    {
        $auth = Yii::$app->authManager;
        $i = 0;
        $data[$i]['name']          = 'table/desktopstatus';
        $data[$i]['rule_name']     = '显示桌台';
        $data[$i++]['description'] = '显示桌台';
        $data[$i]['name']          = 'table/gettableorder';
        $data[$i]['rule_name']     = '获取开单详情';
        $data[$i++]['description'] = '获取开单详情';
        $data[$i]['name']          = 'table/get-table-book';
        $data[$i]['rule_name']     = '获取预定接口';
        $data[$i++]['description'] = '获取预定接口';
        $data[$i]['name']          = 'table/table-goods-turn';
        $data[$i]['rule_name']     = '转台时房间分类和坐台';
        $data[$i++]['description'] = '转台时房间分类和坐台';
        $data[$i]['name']          = 'table/table-turn';
        $data[$i]['rule_name']     = '房间转台';
        $data[$i++]['description'] = '房间转台';
        $data[$i]['name']          = 'table/merge';
        $data[$i]['rule_name']     = '合并房间';
        $data[$i++]['description'] = '合并房间';
        $data[$i]['name']          = 'table/begin-table-book';
        $data[$i]['rule_name']     = '预定';
        $data[$i++]['description'] = '预定';
        $data[$i]['name']          = 'table/begin-table-order-and-book';
        $data[$i]['rule_name']     = '非预定开单';
        $data[$i++]['description'] = '非预定开单';
        $data[$i]['name']          = 'table/begin-table-order';
        $data[$i]['rule_name']     = '开单';
        $data[$i++]['description'] = '开单';
        $data[$i]['name']          = 'table/edit-table';
        $data[$i]['rule_name']     = '修改桌台';
        $data[$i++]['description'] = '修改桌台';
        $data[$i]['name']          = 'table/add-table';
        $data[$i]['rule_name']     = '添加桌台';
        $data[$i++]['description'] = '添加桌台';
        $data[$i]['name']          = 'table/del-table';
        $data[$i]['rule_name']     = '删除桌台';
        $data[$i++]['description'] = '删除桌台';
        $data[$i]['name']          = 'table/edittabletype';
        $data[$i]['rule_name']     = '修改茶座分类';
        $data[$i++]['description'] = '修改茶座分类';
        $data[$i]['name']          = 'table/addtabletype';
        $data[$i]['rule_name']     = '添加茶座分类';
        $data[$i++]['description'] = '添加茶座分类';
        $data[$i]['name']          = 'table/close-table-book';
        $data[$i]['rule_name']     = '取消预定';
        $data[$i++]['description'] = '取消预定';
        $data[$i]['name']          = 'table/deltabletype';
        $data[$i]['rule_name']     = '删除桌台类型';
        $data[$i++]['description'] = '删除桌台类型';
        $data[$i]['name']          = 'goods/list-goods';
        $data[$i]['rule_name']     = '初始化商品数据';
        $data[$i++]['description'] = '初始化商品数据';
        $data[$i]['name']          = 'goods/search-goods';
        $data[$i]['rule_name']     = '商品搜索';
        $data[$i++]['description'] = '商品搜索';
        $data[$i]['name']          = 'table/add-goods';
        $data[$i]['rule_name']     = '添加开单桌台消费';
        $data[$i++]['description'] = '添加开单桌台消费';
        $data[$i]['name']          = 'order/goods-close';
        $data[$i]['rule_name']     = '移除开单桌台消费商品';
        $data[$i++]['description'] = '移除开单桌台消费商品';
        $data[$i]['name']          = 'order/goods-giv';
        $data[$i]['rule_name']     = '商品转赠送 ';
        $data[$i++]['description'] = '商品转赠送 ';
        $data[$i]['name']          = 'vip/create';
        $data[$i]['rule_name']     = '添加会员接口 ';
        $data[$i++]['description'] = '添加会员接口 ';
        $data[$i]['name']          = 'vip/list-vip';
        $data[$i]['rule_name']     = '会员数据获取接口 ';
        $data[$i++]['description'] = '会员数据获取接口 ';
        $data[$i]['name']          = 'vip/search';
        $data[$i]['rule_name']     = 'username ';
        $data[$i++]['description'] = 'username ';
        $data[$i]['name']          = 'vip/pay';
        $data[$i]['rule_name']     = '会员充值 ';
        $data[$i++]['description'] = '会员充值 ';
        $data[$i]['name']          = 'vip/delete';
        $data[$i]['rule_name']     = '会员删除 ';
        $data[$i++]['description'] = '会员删除 ';
        $data[$i]['name']          = 'vip/pay-list';
        $data[$i]['rule_name']     = '会员充值记录 ';
        $data[$i++]['description'] = '会员充值记录 ';
        $data[$i]['name']          = 'vip/print';
        $data[$i]['rule_name']     = '留言模块 ';
        $data[$i++]['description'] = '留言模块 ';
        $data[$i]['name']          = 'message/create';
        $data[$i]['rule_name']     = '添加一条留言 ';
        $data[$i++]['description'] = '添加一条留言 ';
        $data[$i]['name']          = 'message/list-message';
        $data[$i]['rule_name']     = '留言获取列表 ';
        $data[$i++]['description'] = '留言获取列表 ';
        $data[$i]['name']          = 'message/message';
        $data[$i]['rule_name']     = '留言获取列表一条数据 ';
        $data[$i++]['description'] = '留言获取列表一条数据 ';
        $auth = Yii::$app->authManager;
        $admin = $auth->getRole('admin');
        foreach ($data as $val)
        {
            $category = $auth->createPermission($val['name']);
            $category->description = $val['description'];
            $auth->add($category);
            $auth->addChild($admin,$category);
            var_dump($val);
        }
//        $createPost = $auth->createPermission('table/desktopstatus');
//        $createPost->description = 'table/desktopstatus';
//        $auth->add($createPost);
    }
}